apiVersion: v1
kind: Service
metadata:
  name: azure-function-app-service
spec:
  selector:
    app: azure-function-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # This will expose it externally; use NodePort if you're on a local cluster


